# Generated by Django 3.2 on 2021-06-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogcodecs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='dateUploaded',
            field=models.DateTimeField(),
        ),
    ]
