# Generated by Django 3.2 on 2021-06-20 07:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogcodecs', '0003_blogs_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
